service:

  book-app:
    build : .
    container_name: book-app
    ports:
      -"8000:8000"
    env_file:
      - .env
    depends_on:
      -db
    networks:
      -book-network

  db:
    image: postgres:15
    container_name: book-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  ports:
      - "5432:5432"
  volumes:
    - db_data:/var/lib/postgresql/data
  networks:
    - book-network

    
network:
  book-network:

volume:
  book-data:
